# Created by romfrancois
name: Build and deploy

# When workflow is triggered
on: push
  # pull_request:
  #   branches:
  #     - main

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@master

      # Run npm/yarn install
      - name: Install ğŸ”§
        run: yarn install
      
      # Build our code
      - name: Build ğŸ—ï¸
        run: yarn build

      # Deploy to netlify ğŸš€
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
          